# Generated by Django 5.1.6 on 2025-11-29 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0002_enquiry_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enquiry',
            old_name='createdAt',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='enquiry',
            name='messageHistory',
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='adults',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='children',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='hotel',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='location',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='nights',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='travelWith',
            field=models.CharField(max_length=100),
        ),
    ]
