# Generated by Django 5.1.6 on 2025-12-04 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0004_alter_enquiry_adults_alter_enquiry_children_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enquiry',
            name='date',
        ),
        migrations.RemoveField(
            model_name='enquiry',
            name='hotel',
        ),
        migrations.RemoveField(
            model_name='enquiry',
            name='travelWith',
        ),
        migrations.AddField(
            model_name='enquiry',
            name='extra_requirement',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='hotel_category',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='meal',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='selected_package',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='starting_location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='transportation',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='travel_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='travel_group',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='adults',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='children',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='location',
            field=models.CharField(blank=True, default='unknown', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='nights',
            field=models.CharField(blank=True, default='0', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
