# Generated by Django 5.1.6 on 2025-12-04 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0005_remove_enquiry_date_remove_enquiry_hotel_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enquiry',
            old_name='location',
            new_name='email',
        ),
        migrations.RemoveField(
            model_name='enquiry',
            name='meal',
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='nights',
            field=models.IntegerField(default=1),
        ),
    ]
