# Generated by Django 6.0 on 2025-12-09 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0006_rename_location_enquiry_email_remove_enquiry_meal_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enquiry',
            old_name='selected_package',
            new_name='planned_destination',
        ),
        migrations.RemoveField(
            model_name='enquiry',
            name='starting_location',
        ),
    ]
