# Generated by Django 6.0 on 2025-12-10 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0007_rename_selected_package_enquiry_planned_destination_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='adults',
            field=models.CharField(default='1', max_length=10),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='children',
            field=models.CharField(default='0', max_length=10),
        ),
    ]
