# Generated by Django 6.0 on 2025-12-10 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0008_alter_enquiry_adults_alter_enquiry_children'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='starting_location',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
